import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideDrawer from '@/components/SideDrawer'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbar />        
        <div className='flex flex-row'>
          <SideDrawer />
          <div className='w-full bg-[#F5F9FF] p-4 overflow-y-auto'>
            {children}
          </div>          
        </div>        
      </body>
    </html>
  )
}
